[toolchain]
channel = "stable"
targets = [
	"x86_64-unknown-linux-gnu",
	"x86_64-pc-windows-msvc",
	"aarch64-apple-darwin",
	"aarch64-unknown-linux-gnu"
]
components = [
	"clippy",
	"rustfmt",
	"rust-std",
	"cargo",
	"rustc",
	"rust-docs",
	"rust-src",
	"rust-analyzer",
	"llvm-tools"
]
